---
application:
  name: "intern-match"
  project: "intern-match"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "intern-match"
  version: "4.4"
routers:
- name: "main-intern-match"
  routes:
  - application_name: "intern-match"
    paths:
    - "/*"
